### PR TITLE
Fail silently solvers by default

### PR DESCRIPTION
**Pull request by samuelchassot**

### CODE REVIEW

**Comment by samuelchassot** [comment]
@mario-bucev after tracking down the unsupported feature exception with Viktor, we finally found out that we had an option to do exactly what we needed the whole time :) ^^

**Comment by samuelchassot** [comment]
@vkuncak that's ready to merge 👍

**Comment by mario-bucev** [comment]
Aaaaah it was that simple 🙈 good find!

**Comment by vkuncak** [comment]
Did you test this with Stainless? If so, perhaps make a Stainless PR to bump the Inox version?

**Pull request merged**
