### PR TITLE
Improve consistency of command line names

### PR DESCRIPTION
**Pull request by mantognini**
Using `-` to separate words in command line options.

### CODE REVIEW

**Comment by samarion** [comment]
LGTM, but it seems we're still missing `optAssumeChecked` no?

**Comment by mantognini** [comment]
Yes, indeed. I didn't noticed that one because `stainless --help` doesn't list it. [It's being removed from the options actually](https://github.com/epfl-lara/stainless/blob/5439772c19f4fe289f819b9206b8e7ac5a413394/core/src/main/scala/stainless/MainHelpers.scala#L41). I'll update it ASAP.

**Comment by mantognini** [comment]
Done.

**Comment by samarion** [comment]
Looks good to merge.

**Pull request merged**
